#
# Copyright (c) 2001-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

TOPDIR = ..
include $(TOPDIR)/include/builddefs

LSRCFILES = run \
	    apply-mask.test chmod.test computed-mode.test ctime.test \
	    unrepresentable.test basic.test chown.test create.test \
	    delete.test write-vs-append.test

include $(BUILDRULES)

default install install-dev install-lib:
