#! /bin/sh

. $srcdir/tests/test-lib.sh

check 'richacl-apply-masks everyone@:rwpxd::allow' <<EOF
everyone@:rwpxd::allow
EOF

check 'richacl-apply-masks -m 644 everyone@:rwpxd::allow' <<EOF
owner@:rwpd::allow
everyone@:r::allow
EOF

check 'richacl-apply-masks -m 640 everyone@:rwpxd::allow' <<EOF
owner@:rwpd::allow
group@:r::allow
EOF

check 'richacl-apply-masks -m 644 group@:wpd::deny,everyone@:rwpxd::allow' <<EOF
group@:wpd::deny
owner@:rwpd::allow
everyone@:r::allow
EOF

check 'richacl-apply-masks -m 640 group@:wpd::deny,everyone@:rwpxd::allow' <<EOF
group@:wpd::deny
owner@:rwpd::allow
group@:r::allow
EOF

check 'richacl-apply-masks -m 0 everyone@:rwpxd::allow' <<EOF
EOF
