#! /bin/bash

. ${0%/*}/test-lib.sh

require_richacls
use_testdir

ncheck "touch x"
ncheck "setrichacl --set 'owner@:rwp::allow group@:rwp::allow everyone@:r::allow' x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
    group@:rwp----------::allow
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'everyone@:wp::allow owner@:r::allow group@:r::allow' x"
ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
    group@:rwp----------::allow
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'everyone@:wp::deny owner@:rwp::allow group@:rwp::allow' x"
ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
    group@:rwp----------::allow
 everyone@:r------------::allow
EOF

# When checking if an ACL is equivalent to a file mode, the synchronize (S),
# read_attributes (a), and read_acl (c) permissions are completely ignored as
# they are always granted.  The write_attributes (A), write_acl (C), and
# write_owner (o) permissions are ignored for the file owner as they are always
# granted to the file owner.  If the remaining permissions can be exactly
# represented as a file mode, the ACL is not stored as the file mode represents
# an equivalent set of permissions.

# write_data (w) without append_data (p) is not mode-equivalent, so the ACL
# needs to be stored:
ncheck "setrichacl --set 'owner@:rwCo::allow' x"
check "getrichacl x" <<EOF
x:
 owner@:rw-------Co--::allow
EOF

# write_data (w) with append_data (p) is mode-equivalent, so the ACL does not
# need to be stored:
ncheck "setrichacl --set 'owner@:rwpCo::allow' x"
check "getrichacl x" <<EOF
x:
 owner@:rwp----------::allow
EOF

ncheck "chmod 644 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'u:77:rwp::allow' x"
ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
   user:77:rwp----------::allow
    group@:r------------::deny
 everyone@:r------------::allow
EOF

ncheck "chmod 644 x"
check "getrichacl --numeric-ids x" <<EOF
x:
    owner@:rwp----------::allow
   user:77:r------------::allow
    group@:r------------::deny
 everyone@:r------------::allow
EOF

ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
   user:77:rwp----------::allow
    group@:r------------::deny
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'u:77:rwp::allow everyone@:r::allow' x"
ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
   user:77:rwp----------::allow
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'u:77:r::allow everyone@:rwp::allow' x"
ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
   user:77:rwp----------::allow
    owner@:rwp----------::allow
    group@:rwp----------::allow
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'u:77:wp::deny everyone@:rwp::allow' x"
ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
   user:77:-wp----------::deny
    group@:rwp----------::allow
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'u:77:rwp::allow u:77:wp::deny everyone@:rwp::allow' x"
ncheck "chmod 664 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
   user:77:rwp----------::allow
   user:77:-wp----------::deny
    group@:rwp----------::allow
 everyone@:r------------::allow
EOF

ncheck "setrichacl --set 'everyone@:rwp::allow' x"
ncheck "chmod 066 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::deny
 everyone@:rwp----------::allow
EOF

ncheck "chmod 006 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::deny
    group@:rwp----------::deny
 everyone@:rwp----------::allow
EOF

ncheck "chmod 606 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
    group@:rwp----------::deny
 everyone@:rwp----------::allow
EOF

ncheck "setrichacl --set 'u:77:rwp::allow everyone@:rwp::allow' x"
ncheck "chmod 606 x"
check "getrichacl x" <<EOF
x:
    owner@:rwp----------::allow
    group@:rwp----------::deny
 everyone@:rwp----------::allow
EOF

ncheck "chmod 646 x"
check "getrichacl x" <<EOF
x:
   user:77:r------------::allow
    owner@:rwp----------::allow
    group@:-wp----------::deny
   user:77:-wp----------::deny
 everyone@:rwp----------::allow
EOF
