#! /bin/bash

. ${0%/*}/test-lib.sh

require_runas
require_richacls
use_testdir

export LC_ALL=C

# Create directories as root with different permissions
ncheck "mkdir d1 d2 d3"
ncheck "setrichacl --set '99:wx::allow' d2"
ncheck "setrichacl --set '99:px::allow' d3"

runas -u 99 -g 99

# Cannot create files or directories without permissions
check "touch d1/f || :" <<EOF
touch: cannot touch 'd1/f': Permission denied
EOF
check "mkdir d1/d || :" <<EOF
mkdir: cannot create directory 'd1/d': Permission denied
EOF

# Can create files with add_file (w) permission
ncheck "touch d2/f"
check "mkdir d2/d || :" <<EOF
mkdir: cannot create directory 'd2/d': Permission denied
EOF

# Can create directories with add_subdirectory (p) permission
check "touch d3/f || :" <<EOF
touch: cannot touch 'd3/f': Permission denied
EOF
ncheck "mkdir d3/d"
