#! /bin/bash

. ${0%/*}/test-lib.sh

require_runas
use_testdir

export LC_ALL=C

# Undefine the runas wrapper: we use the runas utility directly.
unset runas

init1() {
    rm -rf a b
    mkdir -p a/d b
    touch a/f
    chgrp 99 a a/d b a/f
    # Target file / directory does not exist now.
}

init2() {
    rm -rf a b
    mkdir -p a/d b/d
    touch a/f b/f
    chgrp 99 a a/d b b/d a/f b/f
    # Same as init1, but target file / directory exists now.
}

perms() {
    local mask=$1
    shift

    parent_ncheck "chmod g=$mask $*"
}

umask 077
ncheck "chmod go+rx ."

# Target file / directory does not exist:
init1
check "runas -u 99 -g 99 -- renameat2 a/f b/f || :" <<EOF
Permission denied
EOF

check "runas -u 99 -g 99 -- renameat2 a/d b/d || :" <<EOF
Permission denied
EOF

perms "wx" a b
ncheck "runas -u 99 -g 99 -- renameat2 a/f b/f || :"

check "runas -u 99 -g 99 -- renameat2 a/d b/d || :" <<EOF
Permission denied
EOF

perms "wx" a b
perms "w" a/d
ncheck "runas -u 99 -g 99 -- renameat2 a/d b/d || :"

# Target file / directory exists:
init2
perms "wx" a b
ncheck "runas -u 99 -g 99 -- renameat2 a/f b/f || :"

check "runas -u 99 -g 99 -- renameat2 a/d b/d || :" <<EOF
Permission denied
EOF

perms "w" a/d
ncheck "runas -u 99 -g 99 -- renameat2 a/d b/d || :"

# Swap files / directories:
init2
check "runas -u 99 -g 99 -- renameat2 -x a/f b/f || :" <<EOF
Permission denied
EOF

check "runas -u 99 -g 99 -- renameat2 -x a/d b/d || :" <<EOF
Permission denied
EOF

perms "wx" a b
ncheck "runas -u 99 -g 99 -- renameat2 -x a/f b/f || :"

perms "w" a/d b/d
ncheck "runas -u 99 -g 99 -- renameat2 -x a/d b/d || :"

# Swap file with directory:
init2
check "runas -u 99 -g 99 -- renameat2 -x a/d b/f || :" <<EOF
Permission denied
EOF

perms "wx" a b
perms "w" a/d
ncheck "runas -u 99 -g 99 -- renameat2 -x a/d b/f || :"
