#! /bin/bash

. ${0%/*}/test-lib.sh

require_richacls
use_testdir

umask 022

ncheck "touch f"
ncheck "setrichacl --set 'flags:a 101:w::deny 101:rw::allow 101:w:a:deny 101:rw:a:allow' f"
ncheck "setrichacl --modify '202:w::deny' f"
check "getrichacl --numeric f" <<EOF
f:
 flags:a
   101:-w-----------::deny
   202:-w-----------::deny
   101:rw-----------::allow
   101:-w-----------:a:deny
   101:rw-----------:a:allow
EOF

ncheck "setrichacl --set 'flags:a 101:w::deny 101:rw::allow 101:w:a:deny 101:rw:a:allow' f"
ncheck "setrichacl --modify '202:rw::allow' f"
check "getrichacl --numeric f" <<EOF
f:
 flags:a
   101:-w-----------::deny
   101:rw-----------::allow
   202:rw-----------::allow
   101:-w-----------:a:deny
   101:rw-----------:a:allow
EOF

ncheck "setrichacl --set 'flags:a 101:w::deny 101:rw::allow 101:w:a:deny 101:rw:a:allow' f"
ncheck "setrichacl --modify '202:w:a:deny' f"
check "getrichacl --numeric f" <<EOF
f:
 flags:a
   101:-w-----------::deny
   101:rw-----------::allow
   101:-w-----------:a:deny
   202:-w-----------:a:deny
   101:rw-----------:a:allow
EOF

ncheck "setrichacl --set 'flags:a 101:w::deny 101:rw::allow 101:w:a:deny 101:rw:a:allow' f"
ncheck "setrichacl --modify ' 202:rw:a:allow' f"
check "getrichacl --numeric f" <<EOF
f:
 flags:a
   101:-w-----------::deny
   101:rw-----------::allow
   101:-w-----------:a:deny
   101:rw-----------:a:allow
   202:rw-----------:a:allow
EOF
